# Generated by Django 4.1 on 2022-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('type', models.IntegerField(choices=[(1, 'Foundation'), (2, 'Non governmental organisation'), (3, 'Local Fundraise')], default=1)),
                ('categories', models.ManyToManyField(to='sharepoint.category')),
            ],
        ),
    ]
